development:
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: sberocknroll
  database: urlrecorder

production:
  adapter: postgresql
  encoding: utf8

test:
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: sberocknroll
  database: urlrecorder_test
